### ISSUE TITLE
ImportError: cannot import name 'eval_options'

### ISSUE THREAD

**Issue by Stephenfang51** [RenYurui/Global-Flow-Local-Attention#13]
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    opt = TestOptions().parse()
  File "/input/Global-Flow-Local-Attention/options/base_options.py", line 74, in parse
    opt = self.gather_options()
  File "/input/Global-Flow-Local-Attention/options/base_options.py", line 60, in gather_options
    model_option_set = model.get_option_setter(opt.model)
  File "/input/Global-Flow-Local-Attention/model/__init__.py", line 25, in get_option_setter
    model = find_model_using_name(model_name)
  File "/input/Global-Flow-Local-Attention/model/__init__.py", line 10, in find_model_using_name
    modellib = importlib.import_module(model_file_name)
  File "/usr/local/miniconda3/envs/GFLA/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/input/Global-Flow-Local-Attention/model/face_model.py", line 5, in <module>
    from options import eval_options
ImportError: cannot import name 'eval_options'
```

Please help
just clone the repo and `./setup.sh`, and then run test.py ....etc

**Comment by RenYurui** [comment]
I have fixed the bug. Please try again.
