### ISSUE TITLE
ModuleNotFoundError: No module named 'model.pose_flow_model'

### ISSUE THREAD

**Issue by scparktop** [RenYurui/Global-Flow-Local-Attention#14]
Thank you very much for your good works!
I succeeded to obtain the pose-based transformation results with pre-trained weight and market data.
But, I failed to train when I try to generate ﬂow ﬁelds(the first step of train).
How can I train with market data?(It's same with any other dataset)

----
$ python train.py \
> --name=market \
> --model=pose_flow \
> --attn_layer=2,3 \
> --kernel_size=2=5,3=3 \
> --gpu_id=0 \
> --dataset_mode=market \
> --dataroot=./dataset/market 
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    opt = TrainOptions().parse()
  File "/DeepImage/options/base_options.py", line 74, in parse
    opt = self.gather_options()
  File "/DeepImage/options/base_options.py", line 60, in gather_options
    model_option_set = model.get_option_setter(opt.model)
  File "/DeepImage/model/__init__.py", line 25, in get_option_setter
    model = find_model_using_name(model_name)
  File "/DeepImage/model/__init__.py", line 10, in find_model_using_name
    modellib = importlib.import_module(model_file_name)
  File "/home/psc/anaconda3/envs/gfla/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'model.pose_flow_model'

**Comment by RenYurui** [comment]
Sorry about that. Please use the following code to run the poseflownet_model
``` bash
python train.py \
--name=fashion \
--model=poseflownet \
--attn_layer=2,3 \
--kernel_size=2=5,3=3 \
--gpu_id=0 \
--dataset_mode=fashion \
--dataroot=./dataset/fashion 
```

**Comment by RenYurui** [comment]
If you want to train with the other dataset. You may want to change the --dataset_model (assigns the dataset loader model) and --dataset_root (assigns the root of your set)
for example, if you want to run with the market dataset.
``` bash 
python train.py \
--name=market \
--model=poseflownet \
--attn_layer=2,3 \
--kernel_size=2=5,3=3 \
--gpu_id=0 \
--dataset_mode=market \
--dataroot=./dataset/market
```

**Comment by scparktop** [comment]
Thank you very much!
You are so quick and kind!
It is training very well! ^^
After this training with market dataset, I'll train with my dataset.
Thank you again. ^ ^
