### ISSUE TITLE
Local Variable 'Bi' referenced before assignment

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#37]
Hi Yurui!

I am trying the training code you suggested for Person Animation. I keep running into an error, I'm wondering if you've seen this before.

```
  7%|████████████▋                                                                                                                                                                 | 6/82 [02:42<34:23, 27.15s/it]
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    for i, data in tqdm(enumerate(dataset), total=len(dataset)):
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UnboundLocalError: Traceback (most recent call last):
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/andrewjong/Global-Flow-Local-Attention-VTryon/data/dance_dataset.py", line 211, in __getitem__
    ref_image, ref_skeleton, ref_path = self.gen_ref_image(seq_idx)
  File "/home/andrewjong/Global-Flow-Local-Attention-VTryon/data/dance_dataset.py", line 252, in gen_ref_image
    ref_skeleton = self.load_skeleton(B_path, False)
  File "/home/andrewjong/Global-Flow-Local-Attention-VTryon/data/dance_dataset.py", line 286, in load_skeleton
    return Bi
UnboundLocalError: local variable 'Bi' referenced before assignment
```

I used the same training command you recommended [here](https://github.com/RenYurui/Global-Flow-Local-Attention/issues/32#issuecomment-629176492). I am running on 4 Tesla V100 GPUs.

Thanks for your help.

**Comment by andrewjong** [comment]
It looks like the problematic line is [here](https://github.com/RenYurui/Global-Flow-Local-Attention/blob/5201455027615b2acb15055a13bb6a775bdd34e9/data/dance_dataset.py#L285). 

```python
if len(B_coor)==0:
   pose = torch.zeros(self.opt.structure_nc, self.load_size[0], self.load_size[1])
   # no Bi here
else:
   # Bi gets defined here
return Bi
```

I guess my data has instances where no person is detected. What do you recommend I set Bi to in these cases?

**Comment by andrewjong** [comment]
I think I resolved the problem by just doing this
```python
if len(B_coor)==0:
   pose = torch.zeros(self.opt.structure_nc, self.load_size[0], self.load_size[1])
   Bi = pose
else:
   # Bi also gets defined here
return Bi
```

**Comment by RenYurui** [comment]
Your solution is correct. 
Another way is to pre-process your pose files. You can remove the keypoints that do not contain instances or copy the neighboring skeletons for these empty files.
Besides, our Motion Extraction Net is trained without the empty skeleton files. If you use this network, you may need to do the pre-processing step.
