### ISSUE TITLE
Training: draw_joint() IndexError

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#40]
Hello!

I have another strange error during training.

```
(epoch: 3, iters: 170, time: 2.085) app_gen: 8.081 correctness_p: 2.703 correctness_r: 8.573 content_gen: 6.904 style_gen: 5.742 regularization_p: 0.003 regularization_r: 0.019 ad_gen: 0.668 dis_img_gen: 0.204 
ad_gen_v: 0.711 dis_img_gen_v: 0.201 
saving the latest model (epoch 3, total_steps 170)                                                                                        
  6%|██████▏                                                                                               | 5/82 [01:50<30:19, 23.63s/it]Traceback (most recent call last):
  File "train.py", line 33, in <module>
    for i, data in tqdm(enumerate(dataset), total=len(dataset)):
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/andrewjong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/andrewjong/Global-Flow-Local-Attention-VTryon/data/dance_dataset.py", line 290, in load_skeleton
    color = openpose_utils.draw_joint(color, pose_body.astype(np.int), LIMB_SEQ)
  File "/home/andrewjong/Global-Flow-Local-Attention-VTryon/util/openpose_utils.py", line 153, in draw_joint
    colors[yy, xx] = np.expand_dims(val, 1) * 255
IndexError: index -257 is out of bounds for axis 1 with size 256
```

I find the error confusing because it occurred in the data loader, but it only occurred after a few epochs. This seems to imply it successfully passes through the whole dataset a few times, but then fails for some reason later on. Any idea what this might be? Thanks!

**Comment by andrewjong** [comment]
I am attempting to resolve this with a simple clip. Will report back what happens (might not be for a while because training takes a long time).
```python
yy, xx = np.clip(yy, 0, 255), np.clip(xx, 0, 255)
```

**Comment by RenYurui** [comment]
Thanks for your contribution, would you please send me a pull request?

**Comment by andrewjong** [comment]
Resolved by merge request
