### ISSUE TITLE
ModuleNotFoundError: No module named 'local_attn_reshape_cuda'

### ISSUE THREAD

**Issue by Stephenfang51** [RenYurui/Global-Flow-Local-Attention#7]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from options.test_options import TestOptions
  File "/input/Global-Flow-Local-Attention/options/test_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "/input/Global-Flow-Local-Attention/options/base_options.py", line 4, in <module>
    import model
  File "/input/Global-Flow-Local-Attention/model/__init__.py", line 4, in <module>
    from .base_model import BaseModel
  File "/input/Global-Flow-Local-Attention/model/base_model.py", line 6, in <module>
    from model.networks import base_function
  File "/input/Global-Flow-Local-Attention/model/networks/__init__.py", line 9, in <module>
    from model.networks.discriminator import *
  File "/input/Global-Flow-Local-Attention/model/networks/discriminator.py", line 11, in <module>
    from model.networks.base_function import *
  File "/input/Global-Flow-Local-Attention/model/networks/base_function.py", line 13, in <module>
    from model.networks.local_attn_reshape.local_attn_reshape   import LocalAttnReshape
  File "/input/Global-Flow-Local-Attention/model/networks/local_attn_reshape/local_attn_reshape.py", line 3, in <module>
    import local_attn_reshape_cuda
ModuleNotFoundError: No module named 'local_attn_reshape_cuda'
```
and I check all file under  "local_attn_reshape"

```
(GFLA) root@2ddb824603ac:/input/Global-Flow-Local-Attention/model/networks/local_attn_reshape# ls
local_attn_reshape_cuda.cc    local_attn_reshape_kernel.cuh  __pycache__  test_local_attn_reshape.py
local_attn_reshape_kernel.cu  local_attn_reshape.py          setup.py
```

I excute the ./setup.sh and install extension successfully.
when I try test.py and error.

Thanks !

**Comment by RenYurui** [comment]
Sorry, it is a bug there. Please update the `setup.sh` and try it again.
