### ISSUE TITLE
Colab notebook does not work

### ISSUE THREAD

**Issue by geekmangnu** [RenYurui/Global-Flow-Local-Attention#73]
Hi, because most people do not have suitable GPU colab file is important. Current colab notebook run gives following error below. It seems because of python version which currently is 3.7  and async is reserved word for python 3.7. Changing pose_model.py file by replacing  async to non_blocking resolves it however after fix setup fails. 
`Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    opt = ValOptions().parse()
  File "/content/Global-Flow-Local-Attention/options/base_options.py", line 74, in parse
    opt = self.gather_options()
  File "/content/Global-Flow-Local-Attention/options/base_options.py", line 60, in gather_options
    model_option_set = model.get_option_setter(opt.model)
  File "/content/Global-Flow-Local-Attention/model/__init__.py", line 25, in get_option_setter
    model = find_model_using_name(model_name)
  File "/content/Global-Flow-Local-Attention/model/__init__.py", line 10, in find_model_using_name
    modellib = importlib.import_module(model_file_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/Global-Flow-Local-Attention/model/pose_model.py", line 103
    self.input_P1 = input_P1.cuda(self.gpu_ids[0], async=True)
                                                       ^
SyntaxError: invalid syntax`

after fix it gives another error which seems setup related as follow:

`Loading data pairs ...
Loading data pairs finished ...
dataset [FashionDataset] of size 41 was created
val images = 41
Network [PoseGenerator] was created. Total number of parameters: 14.0474 million. To see the architecture, do print(network).
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu line=225 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    model = create_model(opt)
  File "/content/Global-Flow-Local-Attention/model/__init__.py", line 32, in create_model
    instance = model(opt)
  File "/content/Global-Flow-Local-Attention/model/pose_model.py", line 64, in __init__
    norm='instance', activation='LeakyReLU', extractor_kz=opt.kernel_size)
  File "/content/Global-Flow-Local-Attention/model/networks/__init__.py", line 37, in define_g
    return create_network(netG_cls, opt, **parameter_dic)
  File "/content/Global-Flow-Local-Attention/model/networks/__init__.py", line 28, in create_network
    net.init_weights(opt.init_type)
  File "/content/Global-Flow-Local-Attention/model/networks/base_network.py", line 55, in init_weights
    self.apply(init_func)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 243, in apply
    fn(self)
  File "/content/Global-Flow-Local-Attention/model/networks/base_network.py", line 47, in init_func
    init.orthogonal_(m.weight.data, gain=gain)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/init.py", line 356, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:225`
``

**Comment by radhakrishr36** [comment]
I face the same issues ..How to resolve this error?

RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:225

**Comment by RenYurui** [comment]
Sorry for the delay!
I think it is related to the CUDA version. The Colab CUDA has been improved for the latest. 
I will fix this as soon as possible.

**Comment by geekmangnu** [comment]
> Sorry for the delay!
> I think it is related to the CUDA version. The Colab CUDA has been improved for the latest.
> I will fix this as soon as possible.

Thank you looking forward to try on colab.

**Comment by whuzjw** [comment]
> Sorry for the delay!
> I think it is related to the CUDA version. The Colab CUDA has been improved for the latest.
> I will fix this as soon as possible.

Looking forward to the new version

**Comment by amrzv** [comment]
```
ERROR: Could not find a version that satisfies the requirement torch==1.0.0 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2)
ERROR: No matching distribution found for torch==1.0.0
```
![image](https://github.com/RenYurui/Global-Flow-Local-Attention/assets/36787333/11479cd4-4317-4017-859d-b79efd40c339)
